variables:
# -----------------------------------------------------------------#
# --                   Pipeline Variables                       -- #
# -----------------------------------------------------------------#
# -- Variables used throughout the pipeline
# -- Note: Variable names and files are case sensitive
# --       In YAML files, indentation matters
# -----------------------------------------------------------------#
# --                  Environment Variables                     -- #
# -----------------------------------------------------------------#
# -- The name of the environment
  environmentName: 'dev'                               
# -- Dev Ops Service Connection Name
  serviceConnectionName: 'spntest' 
# -- Terraform Version
  terraformVersion: '0.14.6' 
  
  poolName: DevPool
  # guid for the subscription that the changes are being made in, used in the powershell script. 
  subscriptionID: 3d2593bf-6b49-48fa-a2cc-a1592eaab12e
# -----------------------------------------------------------------#
# --                  Azure Storage Account                     -- #
# -----------------------------------------------------------------#
# Variables for the Azure Storage Account (tfState File Storage)
# -- Azure Storage Account Resource Group Name
  azureStorageAccountRgName: 'rg-ads-eus2-core-dev-ss-001'
# -- Azure Storage Account Region
  azureStorageAccountRegion: 'eastus2'
# -- Azure Storage Account Name (Must be unique in Azure globally)
  azureStorageAccountName: 'saseus2coredevrepo001'
# -- Container Name
  azureStorageAccountContainerName: 'tfstate-cfinfra'

# -----------------------------------------------------------------#
# --                    Terraform Settings                      -- #
# -----------------------------------------------------------------#

# -- Terraform Plan Name
# -- Default is environmentName.plan
  terraformPlanName: $[ format('{0}.plan', variables['environmentName']) ]
# -- Terraform Stage File Name
  terraformStateFileName: 'cfpolicydev.tfstate'
# -- Terraform Subdirectory -- (optional)
# -- Sub directory acts as Terraform working Directory
# -- Comment out the variable below to use the terraform directory as the working directory
  #terraformSubDirectory: $[ format('{0}', variables['environmentName']) ]
# -- Terraform Varialbe File (tfvars) -- Path relative to the working Terraform Directory
# -- If this file doesn't exist a blank one will be created by the pipeline during the Plan Stage
# -- Defaults to blankvarsfile.tfvars
# -- Examples: variables/myvars.tfvars
# -- This is relative to your terraform working directory
  terraformVariableFile: 'variables/dev.tfvars'

# -----------------------------------------------------------------#
# --                     STATIC VARIABLES                       -- #
# --      DO NOT CHANGE -- DO NOT CHANGE -- DO NOT CHANGE       -- #
# -----------------------------------------------------------------# 
# - Instead of YAML conditions using format()
# - Any blank / null values will be removed from the string
  terraformTfVars:              #< -- DO NOT CHANGE
    $[ format('-var-file=./{0}', variables['terraformVariableFile']) ]
  terraformRootDirectory:       #< -- DO NOT CHANGE
    '$(build.artifactstagingdirectory)\build\src\terraform'
#  terraformWorkingDirectory:    #< -- DO NOT CHANGE
#    $[ format('{0}\{1}', variables['terraformRootDirectory'], variables['terraformSubDirectory']) ]
  terraformWorkingDirectory: 
    $[ format('{0}', variables['terraformRootDirectory']) ]
  terraformOutFile:             #< -- DO NOT CHANGE
    $[ format('-out {0}', variables['terraformPlanName']) ]
  terraformCommandOptions:      #< -- DO NOT CHANGE
    $[ format('{0} {1}', variables['terraformOutFile'], variables['terraformTfVars']) ]
# -----------------------------------------------------------------#
# --      DO NOT CHANGE -- DO NOT CHANGE -- DO NOT CHANGE       -- #
# --                     STATIC VARIABLES                       -- #
# -----------------------------------------------------------------# 